const q=document.getElementById('question');const ask=document.getElementById('ask');const status=document.getElementById('status');const result=document.getElementById('result');

ask.onclick=async()=>{const question=q.value.trim();if(!question)return;ask.disabled=true;status.textContent='Checking medication information…';result.classList.add('hidden');try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question})});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Request failed');renderResult(data,question);status.textContent='';}catch(e){status.textContent=e.message}finally{ask.disabled=false}};

function renderResult(data,question){const m=data.medication||{};const title=m.india_brand_name||m.brand_name||m.name||m.india_generic_name||m.generic_name||'Medication information';const composition=m.india_generic_name||m.generic_name||'';const alternatives=(m.india_alternatives||[]).slice(0,6);const purchases=m.purchase_links||[];const sources=data.sources||[];const suggestions=buildSuggestions(m,question);const safety=data.safety||{};
const buy=purchases.length?`<div class="action-row">${purchases.map(x=>`<a class="buy-chip" target="_blank" rel="noreferrer" href="${safeUrl(x.url)}">${escapeHtml(x.name)} <span>↗</span></a>`).join('')}</div>`:'';
const alt=alternatives.length?`<section class="info-section"><div class="section-title">Same-composition brands</div><div class="chip-list">${alternatives.map(x=>`<span class="drug-chip">${escapeHtml(x)}</span>`).join('')}</div><p class="muted">These are identification matches, not automatic therapeutic substitutions.</p></section>`:'';
const suggestionHtml=suggestions.length?`<section class="info-section"><div class="section-title">You may also want to ask</div><div class="suggestion-list">${suggestions.map(x=>`<button class="suggestion" data-q="${escapeAttr(x)}">${escapeHtml(x)} <span>→</span></button>`).join('')}</div></section>`:'';
const sourceHtml=sources.length?`<section class="info-section source-section"><div class="section-title">Sources</div>${sources.slice(0,3).map(s=>`<a class="source-card" target="_blank" rel="noreferrer" href="${safeUrl(s.url)}"><span>${escapeHtml(s.title||s.source_type||'Source')}</span><small>${escapeHtml(s.source_type||'Authoritative source')}</small></a>`).join('')}</section>`:'';
const meta=[m.india_manufacturer&&['Manufacturer',m.india_manufacturer],m.india_strength&&['Strength',m.india_strength],m.india_form&&['Form',m.india_form],m.dosage_form&&['Form',m.dosage_form]].filter(Boolean);
result.innerHTML=`<div class="med-card"><div class="med-hero"><div class="med-icon" aria-hidden="true">Rx</div><div><div class="eyebrow">Medication information</div><h2>${escapeHtml(title)}</h2>${composition&&composition.toLowerCase()!==title.toLowerCase()?`<div class="composition">${escapeHtml(composition)}</div>`:''}</div></div><section class="answer-section"><div class="section-title">What it does</div><div class="answer">${escapeHtml(data.answer)}</div></section>${meta.length?`<div class="facts">${meta.map(([k,v])=>`<div><small>${escapeHtml(k)}</small><strong>${escapeHtml(v)}</strong></div>`).join('')}</div>`:''}${alt}${buy?`<section class="info-section"><div class="section-title">Find this medicine</div>${buy}</section>`:''}${suggestionHtml}<section class="safety ${safety.level==='urgent'?'urgent':''}"><strong>${safety.level==='urgent'?'Seek urgent medical help':'Safety note'}</strong><p>${escapeHtml(safety.disclaimer||'Use medicines according to a qualified healthcare professional’s advice.')}</p></section>${sourceHtml}<div class="quiet-meta">${data.grounded?'Grounded in medication sources':'Source verification unavailable'} · ${escapeHtml(data.provider||'')}</div></div>`;result.classList.remove('hidden');result.querySelectorAll('.suggestion').forEach(b=>b.onclick=()=>{q.value=b.dataset.q;ask.click()});}

function buildSuggestions(m,q){const name=m.india_brand_name||m.brand_name||m.generic_name||m.india_generic_name||q;return [`What is ${name} used for?`,`What are the common side effects of ${name}?`,`How should ${name} be taken?`];}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function escapeAttr(s){return escapeHtml(s).replace(/`/g,'&#96;')}
function safeUrl(s){try{const u=new URL(s,window.location.origin);return ['http:','https:'].includes(u.protocol)?u.href:'#'}catch{return '#'}}